pipeline {
 agent { label "MyAgent1" }

 stages {

 stage('Clone To Agent EC2') {
 steps {
 echo 'Clone the Code from GitHub'
 git url: 'https://github.com/YOUR_GITHUB_USERNAME/YOUR_REPO.git', branch: 'main'
 echo 'Cloning Done'
 }
 }

 stage('Copy') {
 steps {
 echo 'Copy from Jenkin Working Directory To /home/ubuntu/proj Directory'
 sh '''
 rm -rf /home/ubuntu/current/
 mkdir /home/ubuntu/current
 cp -r /home/ubuntu/workspace/* /home/ubuntu/current/
 '''
 echo 'Copy Done'
 }
 }

 stage('Build Docker Image') {
 steps {
 echo 'Start building docker Image'
 sh '''
 cd /home/ubuntu/current
 docker build -t nodejsapi:v1.0 .
 '''
 echo 'Build Complete'
 }
 }

 stage('Run Image As Container') {
 steps {
 echo 'Start building container to Run'
 sh '''
 if lsof -i 5000 -t >/dev/null; then
 echo "Port 5000 is in use, killing process..."
 sudo fuser -k 5000/tcp
 fi
 docker stop nodejsapi-container || true
 docker rm nodejsapi-container || true
 docker run --name nodejsapi-container -d -p 5000:5000 nodejsapi:v1.0
 '''
 echo 'NodeJS API running in a Container(docker)'
 }
 }

 }
}